training_pipeline_config:
  pipeline_name: adult_income_census
  artifact_dir: artifact


# ( Input details to prepare component )

# DataIngestionConfig  ( bring data into system , zip file, split data into train and test)
data_ingestion_config:
  # dataset_download_url: https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.tgz
  dataset_download_url: kaggle datasets download -d overload10/adult-census-dataset.tgz
  raw_data_dir: raw_data
  tgz_download_dir: tgz_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test 



# DataValidationConfig ( schema validation , filename, no.columns, data type of columns)
data_validation_config:
  schema_dir: config
  schema_file_name: schema.yaml
  report_file_name: report.json
  report_page_file_name: report.html


# DataTransformationConfig ( feature engineering stuff  : Generate pickle file )
data_transformation_config:
  # add_bedroom_per_room: true
  transformed_dir: transformed_data
  transformed_train_dir: train
  transformed_test_dir: test
  preprocessing_dir: preprocessed
  preprocessed_object_file_name: preprocessed.pkl
  

# ModelTrainerConfig ( model training  : Generate pickle file )  
model_trainer_config:
  trained_model_dir: trained_model
  model_file_name: model.pkl
  base_accuracy: 0.6
  model_config_dir: config
  model_config_file_name: model.yaml


# ModelEvaluationConfig ( evaluate model using test data )
model_evaluation_config:
  model_evaluation_file_name: model_evaluation.yaml
  

# ModelPusherConfig (  push model to cloud )
model_pusher_config:
  model_export_dir: saved_models
